using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerAudio : MonoBehaviour
{
    public AudioSource walkSource;      // ื฿ยทษ๙า๔ตฤAudioSource
    public AudioSource actionSource;    // ทญน๖บอนฅป๗ตฤAudioSource
    public AudioClip walkClip;          // ื฿ยทษ๙า๔ตฤAudioClip
    public AudioClip rollClip;          // ทญน๖ษ๙า๔ตฤAudioClip
    //public AudioClip attackClip;        // นฅป๗ษ๙า๔ตฤAudioClip
    public AudioClip jumpClip;          // ฬ๘ิพษ๙า๔ตฤAudioClip

    private float lastAttackTime = 0;   // ษฯาปดฮนฅป๗ษ๙า๔ฒฅทลตฤสฑผไ
    private bool canRoll = true;        // สวท๑ฟษาิฒฅทลทญน๖ษ๙า๔
    private bool canJump = true;        // สวท๑ฟษาิฒฅทลฬ๘ิพษ๙า๔

    void Update()
    {
        HandleWalking();
        HandleRolling();
        HandleJumping();
        //HandleAttacking();
    }

    void HandleWalking()
    {
        if (Input.GetKey(KeyCode.W) || Input.GetKey(KeyCode.A) ||
            Input.GetKey(KeyCode.S) || Input.GetKey(KeyCode.D))
        {
            if (!walkSource.isPlaying)
            {
                walkSource.clip = walkClip;
                walkSource.loop = true;
                walkSource.Play();
            }
        }
        else
        {
            if (walkSource.isPlaying)
            {
                walkSource.Stop();
            }
        }
    }

    void HandleRolling()
    {
        if (Input.GetKeyDown(KeyCode.F) && canRoll)
        {
            PlaySoundLimited(rollClip, 1f);
            canRoll = false;
            StartCoroutine(ActionCooldown(() => canRoll = true, 0.5f));
        }
    }

    void HandleJumping()
    {
        if (Input.GetKeyDown(KeyCode.Space) && canJump)
        {
            PlaySoundLimited(jumpClip, 1f);
            canJump = false;
            StartCoroutine(ActionCooldown(() => canJump = true, 0.5f));
        }
    }

    /*void HandleAttacking()
    {
        if (Input.GetMouseButtonDown(0) && Time.time - lastAttackTime >= 2.0f)
        {
            actionSource.PlayOneShot(attackClip);
            lastAttackTime = Time.time;
        }
    }*/

    void PlaySoundLimited(AudioClip clip, float duration)
    {
        actionSource.PlayOneShot(clip);
        StartCoroutine(StopSoundAfterDuration(actionSource, duration));
    }

    IEnumerator StopSoundAfterDuration(AudioSource source, float duration)
    {
        yield return new WaitForSeconds(duration);
        source.Stop();
    }

    IEnumerator ActionCooldown(System.Action onComplete, float delay)
    {
        yield return new WaitForSeconds(delay);
        onComplete();
    }
}
